### ISSUE TITLE
Question: Time-period for CMIP scores

### ISSUE THREAD

**Issue by mattphysics** [JanStreffing/cmpitool#50]
Thanks for the great tool!

I have a clarification question - over which period are the scores in "eval" computed? I could not find an explicit explanation in the documentation. Is it over the "default" time period (198912-201411) of the cmpitool function?

Would be great to have an indication.

Thanks
Matthias

**Comment by JanStreffing** [comment]
The CMIP6 model eval period is always 198912-201411, so the last 25 years worth of fully available seasons (DJF,MAM,JJA,SON). I will add a note stating this in the documentation. On the observations/reanalys side I tried to match that period as well as possible, but it did not always prove possible: https://github.com/JanStreffing/cmpitool/blob/master/obs/obs_periods.txt

**Comment by JanStreffing** [comment]
I've added an FAQ section and this question as the first one therein:
https://cmpitool.readthedocs.io/en/latest/faq.html
(you may have to delete your browser cache for the website to reload properly, I had to)
